" Basic settings
syntax on

" Misc settings
" set guifont=M+\ 1m\ Medium\ 12
" set guifont=Ubuntu\ Mono\ derivative\ Powerline\ 12
set guifont=Meslo\ LG\ S\ DZ\ for\ Powerline\ 10

" GUI options
set guioptions-=L
set guioptions-=l
set guioptions-=R
set guioptions-=r
set guioptions-=T
set guioptions-=m

" Disable blink cursor
set guicursor+=a:blinkon0

" Disable cursorline
set nocursorline
