" ######################################################################################################################
" ### Author : Martin Toma <martin.toma.svk@gmail.com>                                                               ###
" ######################################################################################################################
" ### VIMRC Configuration focused on RAILS development                                                               ###
" ### Date created : Tue Nov 12 14:14:56 CET 2013                                                                    ###
" ######################################################################################################################

" ======================================================================================================================
" 1.0 Plugin manager (Plug) settings
" ======================================================================================================================
"{{{

call plug#begin('~/.vim/plugged')

" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
" 1.1 Plugin list
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

" ---------------------------------------------------------------------------------------------------------------------
" 1.1.1 Language or framework supporting plugins
" ---------------------------------------------------------------------------------------------------------------------

" -----------------------------------------------------
" 1.1.1.1 Universal
" -----------------------------------------------------
" Most common languages support (syntax, indenting, etc. ) for ruby, js, etc.
Plug 'sheerun/vim-polyglot'
" Needs linters to be installed to work properly (see https://github.com/scrooloose/syntastic/wiki/Syntax-Checkers)
Plug 'scrooloose/syntastic', { 'for': ['java', 'ruby', 'eruby', 'coffee', 'javascript', 'html'] }

" -----------------------------------------------------
" 1.1.1.2 Ruby/Rails
" -----------------------------------------------------
" Rails navigation, etc. plugin (f.e. :Rmigration)
Plug 'tpope/vim-rails', { 'for': ['ruby', 'eruby'] }
" Automatically inserts 'end' wisely
Plug 'tpope/vim-endwise', { 'for': ['ruby', 'eruby'] }
" Splitting and joining multiple lines ruby constructs
Plug 'AndrewRadev/splitjoin.vim', { 'for': ['ruby', 'eruby'] }
" Ruby eval plugin
Plug 'kmdsbng/vim-ruby-eval', { 'for': ['ruby', 'eruby'] }
" Change between ruby 1.9 and 1.8 hash syntax
Plug 'ck3g/vim-change-hash-syntax', { 'for': ['ruby', 'eruby'] }
" Refactoring tools
Plug 'ecomba/vim-ruby-refactoring', { 'for': ['ruby', 'eruby'] }
" Ruby best practices checker
Plug 'ngmy/vim-rubocop', { 'for': ['ruby', 'eruby'] }

" -----------------------------------------------------
" 1.1.1.3 HTML/CSS/JS
" -----------------------------------------------------
" CSS color highlighter
Plug 'ap/vim-css-color', { 'for': ['css', 'sass', 'less'] }
" JS libs syntax files, ember, angular, etc.
Plug 'othree/javascript-libraries-syntax.vim', { 'for': ['javascript', 'coffee'] }
" Sparkup, emmet alternative (<C-e> to expand expression)
Plug 'rstacruz/sparkup', { 'for': ['html', 'xhtml']}

" -----------------------------------------------------
" 1.1.1.4 Android
" -----------------------------------------------------
" Android build and deploy helpers
Plug 'hsanson/vim-android', { 'for': 'java' }

" ---------------------------------------------------------------------------------------------------------------------
" 1.1.2 Motion/code navigation improving plugins
" ---------------------------------------------------------------------------------------------------------------------

" Camel case motion
Plug 'bkad/CamelCaseMotion'
" Seek, easy motion for long lines
Plug 'goldfeld/vim-seek'
" Improved incremental search
Plug 'haya14busa/incsearch.vim'

" ---------------------------------------------------------------------------------------------------------------------
" 1.1.3 Text insertion improving plugins
" ---------------------------------------------------------------------------------------------------------------------

" Snipmate stype snippets support
Plug 'garbas/vim-snipmate'
" Multiple cursors feature
Plug 'terryma/vim-multiple-cursors'
" Supertab (autocomplete) plugin
Plug 'ervandew/supertab'
" Auto-closing brackets and quotes
Plug 'Raimondi/delimitMate'

" ---------------------------------------------------------------------------------------------------------------------
" 1.1.4 Interface improving plugins
" ---------------------------------------------------------------------------------------------------------------------

" Unite (Files, Buffers, Commands, etc. fuzzy searcher)
Plug 'Shougo/unite.vim'
" Nerdtree file browser
Plug 'scrooloose/nerdtree'
" Airline (improved status line)
Plug 'bling/vim-airline'
" Tags (methods, classes) display window
Plug 'majutsushi/tagbar'
" Distraction free editing
Plug 'junegunn/goyo.vim'

" ---------------------------------------------------------------------------------------------------------------------
" 1.1.5 Git/Github support plugins
" ---------------------------------------------------------------------------------------------------------------------

" Git wrapper
Plug 'tpope/vim-fugitive'
" Git changes visualizer
Plug 'airblade/vim-gitgutter'
" Gitk for vim
Plug 'gregsexton/gitv'

" ---------------------------------------------------------------------------------------------------------------------
" 1.1.6 Text objects improving plugins
" ---------------------------------------------------------------------------------------------------------------------
"
" Matchit better textobj support
Plug 'tmhedberg/matchit'
" Change surroundings characters
Plug 'tpope/vim-surround'
" Expanding region selection
Plug 'terryma/vim-expand-region'

" ---------------------------------------------------------------------------------------------------------------------
" 1.1.7 Color-scheme plugins
" ---------------------------------------------------------------------------------------------------------------------

" Molokai theme
Plug 'tomasr/molokai'
" Hybrid dark color theme
Plug 'w0ng/vim-hybrid'
" Approximation to make gvim schemes work in terminal
Plug 'vim-scripts/CSApprox'

" ---------------------------------------------------------------------------------------------------------------------
" 1.1.8 Dependencies
" ---------------------------------------------------------------------------------------------------------------------

" Async processing (for Unite) (make after checkout)
Plug 'Shougo/vimproc.vim'
" Dependency for vim-snipmate
Plug 'marcweber/vim-addon-mw-utils'
" Dependency for vim-snipmate
Plug 'tomtom/tlib_vim'

" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
" 1.2 End of plugin declaration
" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
call plug#end()
"}}}

" ======================================================================================================================
" 2.0 Basic settings
" ======================================================================================================================
"{{{

set shell=/bin/bash                         " Setting shell to bash
set nocompatible                            " No compatible with vi mode
set relativenumber                          " Relativeline numbers
set ignorecase                              " Don't ignore cases
set smartcase                               " Make search case sensitive only if it contains uppercase letters
set laststatus=2                            " Always show status line
set showmode                                " Always show mode
set wildmenu                                " Better auto-complete of ex commands
set textwidth=120                           " Text width is 120 chars
set autoread                                " Automatically reload change files on disk
set cursorline                              " Set default cursor line (highlighting is done by color scheme)
set cmdheight=1                             " Command line height
set pumheight=10                            " Completion window max size
set iskeyword-=_                            " Set underscore as a word separator
set iskeyword-=-                            " Set dash as a word separator
set timeoutlen=200                          " Setting ESC timeout
set hlsearch                                " Highlight search
set incsearch                               " Incremental search
set hidden                                  " Enables to switch between unsaved buffers and keep undo history
set undolevels=100                          " How many undo commands to remember
set clipboard+=unnamed                      " Use system clipboard
set history=1024                            " Number of things to remember in history
set nohlsearch                              " Don't highlight after search
set mat=2                                   " How many tenths of a second to blink when matching brackets
set lazyredraw                              " Don't redraw while executing macros (better performance)
set magic                                   " For regular expressions turn magic on
set showmatch                               " Show matching brackets when text indicator is over them
set encoding=utf8                           " Set utf8 as standard encoding and en_US as the standard language
set pastetoggle=<F3>                        " Toggle between paste and nopaste
set nolist                                  " Dont display whitechars by default (use F7)
set spelllang=en_us                         " Set language to us English
set backspace=indent,eol,start              " Set default behaviour of backspace
set spellfile=~/.vim/dictionary.utf-8.add   " Use this file for spell checking
set nostartofline                           " Prevent cursor from moving to beginning of line when switching buffers
set virtualedit=block                       " To be able to select past EOL in visual block mode
set nojoinspaces                            " No extra space when joining a line which ends with . ? !
set startofline                             " When doing thing like gg or G, will move cursor to start of line
set wrapscan                                " Search again from top when reached the bottom
set showcmd                                 " Show incomplete commands
set scrolloff=5                             " Scroll when closing to top or bottom of the sceeen

" -----------------------------------------------------
" 2.1 Intendation settings (2 spaces tabs)
" -----------------------------------------------------
set autoindent
set expandtab
set shiftwidth=2
set softtabstop=2

" -----------------------------------------------------
" 2.2 Split settings (more natural).
" -----------------------------------------------------
set splitbelow
set splitright

" -----------------------------------------------------
" 2.3 Turn backup off, since most stuff is in git
" -----------------------------------------------------
set nobackup
set nowb
set noswapfile

" -----------------------------------------------------
" 2.4 Highlight whitespaces
" -----------------------------------------------------
set listchars=tab:▸\ ,trail:.,extends:#,nbsp:.,eol:¬

" -----------------------------------------------------
" 2.5 Filetype settings
" -----------------------------------------------------
syntax on
filetype off
filetype plugin on
filetype indent on

" -----------------------------------------------------
" 2.6 Folding settings, by default is disabled, use 'za'
" -----------------------------------------------------
set foldmethod=marker
set foldlevelstart=2
set fillchars="fold: "

" -----------------------------------------------------
" 2.7 Enable omni completion. (Ctrl-X Ctrl-O)
" -----------------------------------------------------
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType c set omnifunc=ccomplete#Complete
autocmd FileType java set omnifunc=javacomplete#Complete
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading=1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global=1
autocmd FileType ruby,eruby let g:rubycomplete_rails=1
autocmd FileType ruby,eruby let g:rubycomplete_load_gemfile=1

" make CSS omni-completion work for SASS and SCSS
autocmd BufNewFile,BufRead *.scss             set ft=scss.css
autocmd BufNewFile,BufRead *.sass             set ft=sass.css

" use syntax complete if nothing else available
if has("autocmd") && exists("+omnifunc")
  autocmd Filetype *
        \ if &omnifunc == "" |
        \         setlocal omnifunc=syntaxcomplete#Complete |
        \ endif
endif

" -----------------------------------------------------
" 2.8 Completion ignore list
" -----------------------------------------------------
set wildignore=*.o,*.obj,*~
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif
"}}}

" ======================================================================================================================
" 3.0 Mapping settings
" ======================================================================================================================
"{{{

" -----------------------------------------------------
" 3.1 Setting leader
" -----------------------------------------------------
let mapleader="\<space>"
let g:mapleader="\<space>"

" -----------------------------------------------------
" 3.2 Disabling arrow keys, space key, exmode enter
" with Q key, help with F1
" -----------------------------------------------------
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
nnoremap <bs> <nop>
nnoremap <delete> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap <Space> <nop>
nnoremap <F1> <nop>
nnoremap Q <nop>

" -----------------------------------------------------
" 3.3 Defaults overriding
" -----------------------------------------------------

" When jump to next match also center screen
noremap n nzz
noremap N Nzz

" Same when moving up and down
noremap <c-d> <c-d>zz
noremap <c-u> <c-u>zz

" Remap H and L (top, bottom of screen to left and right end of line)
nnoremap H ^
nnoremap L $
vnoremap H ^
vnoremap L $

" More logical Y (defaul was alias for yy)
nnoremap Y y$

" Quick replay q macro
nnoremap Q @q

" -----------------------------------------------------
" 3.4 Common task mappings
" -----------------------------------------------------

" Quick save and quit / buffer delete
nnoremap ,w :w<CR>
nnoremap <silent> ,q :q<CR>
nnoremap <silent> ,d :bd<CR>
nnoremap <silent> + :bn<CR>
nnoremap <silent> _ :bp<CR>

" Bubble single lines
nnoremap <C-k> ddkP
nnoremap <C-j> ddp

" Bubble multiple lines
vnoremap <C-j> xp`[V`]
vnoremap <C-k> xkP`[V`]

" Reformat whole file easily
nnoremap <silent> ,r mzgg=G`z

" Insert line break (opposite of J-join lines)
nnoremap ,j i<CR><ESC>

" Quoting visually selected area with "
" TODO: wrap to function and support multiline selections
vnoremap " c''<ESC>hp

" Shortcuts for quiting and saving
cmap ww wqall
cmap qq qall

" Command abbreviations to accept case errors
cab W! w!
cab Q! q!
cab Wq wq
cab Wa wa
cab wQ wq
cab WQ wq
cab W w
cab Q q

" -----------------------------------------------------
" 3.5 Toggles setup
" -----------------------------------------------------

" Toggle nerdtree (file browser) panel
nnoremap <silent> <F1> :NERDTreeToggle<CR>
" Toggle tagbar (methods, classes, etc.) window
nnoremap <silent> <F2> :NERDTreeFind<CR>
" Toggle spelling on and off
nnoremap <silent> <F4> :set spell!<CR>
" Source (reload) vimrc, so new setting will be applied
nnoremap <silent> <F5> :source $MYVIMRC<CR>
" Open my vimrc in new tab
nnoremap <silent> <F6> :tabedit $MYVIMRC<CR>
" Toggle white characters visibility
nnoremap <silent> <F7> :set list!<CR>
" Toggle syntax checking
nnoremap <silent> <F8> :SyntasticToggleMode<CR>
" Toggle rainbow paranthesis
nnoremap <silent> <F9> :RainbowParenthesesToggle<CR>
" Toggle Goyo mode
nnoremap <silent> <F10> :Goyo<CR>
" Toggle tagbar (methods, classes, etc.) window
nnoremap <silent> <F11> :TagbarToggle<CR>
" Echo out toggles legend on <F12>
nnoremap <F12> :call ShowToggles()<CR>

" -----------------------------------------------------
" 3.6 Window management mappings
" -----------------------------------------------------

" Resizing using arrow keys
nnoremap <silent> <Left> :vertical resize -1<CR>
nnoremap <silent> <Right> :vertical resize +1<CR>
nnoremap <silent> <Up> :resize +1<CR>
nnoremap <silent> <Down> :resize -1<CR>
"}}}

" ======================================================================================================================
" 4.0 Plugins settings
" ======================================================================================================================
"{{{

" -----------------------------------------------------
" 4.1 Airline (status line)
" -----------------------------------------------------
let g:airline#extensions#tabline#left_sep=' '
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#left_alt_sep='|'
let g:airline_powerline_fonts=1
let g:airline_exclude_preview=1

" -----------------------------------------------------
" 4.2 Nerdtree (file browser) setting
" -----------------------------------------------------
let NERDTreeMinimalUI=1
let NERDTreeDirArrows=1
let g:NERDTreeWinSize=40

" -----------------------------------------------------
" 4.3 Unite
" -----------------------------------------------------

" Matcher settings
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])
call unite#custom#source('file_rec/async','sorters','sorter_rank')

" Track yank history
let g:unite_source_history_yank_enable=1

" Use ag if available
if executable('ag')
  let g:unite_source_grep_command='ag'
  let g:unite_source_grep_default_opts='--nocolor --line-numbers --nogroup -S -C4'
  let g:unite_source_grep_recursive_opt=''
  " Ignore vcs files
  let g:unite_source_rec_async_command='ag --nocolor --nogroup --ignore ".hg" --ignore ".svn" --ignore ".git" --ignore ".bzr" --hidden -g ""'
endif

" Ignore wildignore files
call unite#custom#source('file_rec', 'ignore_globs', split(&wildignore, ','))

" Custom profile
call unite#custom#profile('default', 'context', {
\   'prompt': '» ',
\   'winheight': 15,
\ })

" -----------------------------------------------------
" 4.4 Syntastic (syntax checker)
" -----------------------------------------------------
let g:syntastic_ruby_checkers=['mri']
" mark syntax errors with :signs
let g:syntastic_enable_signs=1
" automatically jump to the error when saving the file
let g:syntastic_auto_jump=0
" show the error list automatically
let g:syntastic_auto_loc_list=1
" check on open as well as save
let g:syntastic_check_on_open=1
" don't care about warnings
let g:syntastic_quiet_messages={'level': 'warnings'}
" Passive mode is default
let g:syntastic_mode_map={ 'mode': 'passive', 'active_filetypes': [],'passive_filetypes': [] }
" Disable csslint, scss and sass syntax checking is not behaving correctly
let g:loaded_syntastic_css_csslint_checker=0

" -----------------------------------------------------
" 4.5 Tagbar (methods, classes, etc. browser)
" -----------------------------------------------------
let g:tagbar_type_ruby={
      \ 'kinds' : [
      \ 'm:modules',
      \ 'c:classes',
      \ 'd:describes',
      \ 'C:contexts',
      \ 'f:methods',
      \ 'F:singleton methods'
      \ ]
      \ }

" -----------------------------------------------------
" 4.7 Supertab
" -----------------------------------------------------
let g:SuperTabDefaultCompletionType='<C-p>'

" -----------------------------------------------------
" 4.8 Goyo
" -----------------------------------------------------
let g:goyo_width=120
let g:goyo_margin_top=2
let g:goyo_margin_bottom=2
"}}}

" ======================================================================================================================
" 5.0 Plugin mappings
" ======================================================================================================================
"{{{
" -----------------------------------------------------
" 5.1 Unite and extensions
" -----------------------------------------------------

" Custom mappings for the unite buffer
autocmd FileType unite call s:unite_settings()
function! s:unite_settings()
  " Play nice with supertab
  let b:SuperTabDisabled=1
  " Enable navigation with control-j and control-k in insert mode
  imap <silent> <buffer> <C-j> <Plug>(unite_select_next_line)
  imap <silent> <buffer> <C-k> <Plug>(unite_select_previous_line)
  " Runs 'splits' action by <C-s> and <C-v>
  imap <silent> <buffer> <expr> <C-s> unite#do_action('split')
  imap <silent> <buffer> <expr> <C-v> unite#do_action('vsplit')
  " Exit with escape
  nmap <buffer> <ESC> <Plug>(unite_exit)
endfunction

" Search in buffer
nnoremap <silent> <leader><leader> :<C-u>Unite -no-split -buffer-name=buffers buffer<CR>
" Search in cwd files recursively
nnoremap <silent> <leader>o :<C-u>UniteWithCurrentDir -no-split -buffer-name=files -start-insert file_rec/async:!<CR>
" Search for term in cwd file
nnoremap <silent> <leader>/ :<C-u>Unite grep:.<CR>
" Search in commands
nnoremap <silent> <leader>c :<C-u>Unite -start-insert command<CR>
" Search in defined mappings
nnoremap <silent> <leader>m :<C-u>Unite -start-insert mapping<CR>
" Search in yank history
nnoremap <silent> <leader>y :<C-u>Unite -no-split -buffer-name=yank-history history/yank<CR>

" -----------------------------------------------------
" 5.2 Surround shortcut for quotes changing
" -----------------------------------------------------
nmap cq cs"'
nmap cQ cs'"

" -----------------------------------------------------
" 5.3 Expand region
" -----------------------------------------------------
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)

" -----------------------------------------------------
" 5.4 Ruby eval
" -----------------------------------------------------
nnoremap <silent> ,r :RubyEval<CR>

" -----------------------------------------------------
" 5.5 Camel case motion mapping (replace default w b e)
" -----------------------------------------------------
map <silent> w <Plug>CamelCaseMotion_w
map <silent> b <Plug>CamelCaseMotion_b
map <silent> e <Plug>CamelCaseMotion_e
" Unmap old to not conflict
sunmap w
sunmap b
sunmap e

" -----------------------------------------------------
" 5.6 Improved incremental search
" -----------------------------------------------------
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
"}}}

" ======================================================================================================================
" 6.0 Color and highlighting settings
" ======================================================================================================================
"{{{
" XTerm 256 colors
if $TERM == 'xterm-256color' || 'screen-256color'
  set t_Co=256
endif

" Dark background as default
set bg=dark

" Color scheme changing based on time
if strftime("%H") < 16
  let g:molokai_original=1
  let g:rehash256=1
  colorscheme molokai
  let g:airline_theme='tomorrow'
else
  colorscheme hybrid
  let g:airline_theme='bubblegum'
endif

" Color column
let &colorcolumn=121

" Git gutter (signcolumn color)
highlight clear SignColumn

" Remove underline in folded lines
hi Folded term=NONE cterm=NONE gui=NONE ctermbg=NONE
"}}}

" ======================================================================================================================
" 7.0 Filetype specific settings
" ======================================================================================================================
"{{{
autocmd FileType php setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType ruby setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType php setlocal tabstop=4 shiftwidth=4 softtabstop=4 textwidth=120
autocmd FileType coffee,javascript setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4 textwidth=120
autocmd FileType html,htmldjango,xhtml,haml setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=0
autocmd FileType sass,scss,css setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType vim setlocal keywordprg=:help
"}}}

" ======================================================================================================================
" 8.0 Custom functions and autocommands
" ======================================================================================================================
"{{{
" Close vim if the last open window is nerdtree
autocmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" Hide cursorlines when focus lost
autocmd BufEnter * set cursorline
autocmd BufLeave * set nocursorline

" Remove trailing whitespaces automatically before save
autocmd BufWritePre * :%s/\s\+$//e

function! ShowToggles()
  echom "| <F1> NerdTree | <F2> NerdTreeFind | <F3> Paste mode | <F4> Spellcheck | <F5> Source .rc | <F6> Edit .rc |" .
        \"<F7> Whitechars | <F8> Syntastic | <F9> Rainbow() | <F10> Goyo mode | <F11> Tagbar | <F12> This message |"
endfunction
"}}}
" ======================================================================================================================
" TODO LIST:
" ======================================================================================================================
"{{{
"
" 1. Really start writing this vimrc help file on github.
"
"}}}
